M48
; DRILL file {KiCad 9.0.5} date 2025-10-15T09:52:21+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-15T09:52:21+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X103.35Y-113.43
X103.35Y-119.21
T2
X64.0Y-94.0
X106.0Y-136.0
M30
